# Site settings
title: 2030 Watch
url: https://2030-watch.de
staticurl: /static/

contact:
  - mail: 2030-Watch@okfn.de
  - phone: "+49 30 57703666-0"
  - fax: "Fax: +49 30 57703666-9"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: FF6640
  primary-rgb: "255,102,64" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/2030WatchDe
  - title: github
    url: https://github.com/okfde/2030-watch.de

# Postal address (add as many lines as necessary)
address:
  - line: Open Knowledge Foundation Deutschland e.V.
  - line: Singerstr. 109, 10179 Berlin, Deutschland

organisation:
  - line: "Vereinsregister Nr: VR 30468 B"
  - line: "Steuernummer: 27/674/52428"
  - line: "VAT: DE278022128"

# Build settings
markdown: kramdown
permalink: pretty

paginate: 8
paginate_path: blog/page/:num/

languages: ["de", "en"]
default_lang: "de"
exclude_from_localization: ["static"]
parallel_localization: true

gems: [jekyll-paginate, jekyll-polyglot]

exclude: ['Gemfile*', 'CNAME', 'README.md']

sass:
  sass_dir: static/style/_sass
  style: compressed

collections:
  - sdgs

indicatorarray: []

t:
  intromsg:
    en: >
      All member countries of the United Nations have agreed to implement
      the global sustainable development goals by 2030. 2030Watch assesses
      if rich countries adhere to this promise.
    de: >
      Deutschland hat sich verpflichtet bis 2030 die globalen
      Nachhaltigkeits-Ziele der Vereinten Nationen zu erreichen. 2030 Watch
      überprüft, ob dieses Versprechen eingehalten wird.
  tomonitoringtool:
    en: Check out the Monitoring Tool
    de: Zum Monitoring Tool
  topmsg:
    en: Are we becoming more sustainable?
    de: Wird Deutschland nachhaltig?
  longintrotext:
    en: >
      In September 2015 193 countries created the global goals for sustainable
      development to be attained in the next 15 years. The goals cover environmental,
      social and economic topics as well as political aspects such as transparency
      and democracy. 2030 Watch asseses how far along we are to achieving these goals
      using over 60 indicators.
    de: >
      Im September 2015 haben 193 Staaten die globalen Ziele für
      nachhaltige Entwicklung verabschiedet, die in den nächsten 15
      Jahren erreicht werden sollen. Diese Ziele umfassen ökologische,
      soziale und ökonomische Themen, aber auch politische Aspekte
      wie Transparenz und Bürgerbeteiligung. Auf 2030 Watch wird
      anhand von über 60 Indikatoren aufgezeigt, wie weit wir von
      diesen Zielen entfernt sind.
  moreblogs:
    en: More blog posts
    de: Weitere Blogeinträge
  methodology:
    en: Methodology
    de: Methodisches Vorgehen
  understand:
    en: Understand
    de: Verstehen
  germanysimplementation:
    en: Germany's implementation of the Sustainable Development Goals (SDGs)
    de: Deutschlands Umsetzung der Ziele für nachhaltige Entwicklung
  indicators:
    en: Indicators
    de: Indikatoren
  longmainviztext:
    en: >
      Each square represents one indicator for the implementation
      of the 2030 Agenda in Germany. The colours represent the
      level of sustainability achieved for the indicator.
      Click on one of the 17 goals and check out the relevant indicators.
      You can also filter the indicators and see who proposes a given indicator.
    de: >
      In dieser Visualisierung repräsentiert jeder Punkt einen Indikator
      für das Erreichen der Ziele für nachhaltige Entwicklung durch Deutschland.
      Die Farben zeigen dabei an wie nachhaltig Deutschland aktuell im jeweiligen
      Indikator ist. Klicke auf eines der 17 Ziele und sieh alle Indikatoren zum
      ausgewählten Ziel. Unter Indikatorquelle kannst Du offizielle Indikatoren
      von unseren Vorschlägen unterscheiden - Probier’s mal aus! 
  indicatorsfiltertext:
    en: Filter indicators by
    de: Indikatoren filtern nach
  indicatorsource:
    en: Indicator source
    de: Indikatorquelle
  resetfilter:
    en: Reset filters
    de: Filter zurücksetzen
  officialindicators:
    en: official indicators
    de: offizielle Indilkatoren
  ourindicators:
    en: our indicators
    de: eigene Indikatoren
  officialinofficialtext:
    en: >
      2030-Watch contains offical and unofficial indicators. The official indicators
      contain suggestions from the Expert Group on SDG Indicators, the Sustainable
      Development Solutions Network and the German strategy for sustainability.
      The inofficial indicators represent suggestions from the Open Knowledge Foundation
      Germany. These suggestions have been developed partly in collaboration with
      civil society experts.
    de: >
      2030-Watch enthält offizielle Indikatoren und inoffizielle Indikatoren.
      Die offiziellen Indikatoren umfassen Vorschläge der UN Expertengruppe
      für Indikatorvorschläge, des Sustainable Development Solutions Networks
      und der bestehenden deutschen Nachhaltigkeitsstrategie. Die inoffiziellen
      Indikatoren stellen Indikatorvorschlag der Open Knowledge Foundation dar.
      Diese Vorschläge sind zum Teil in Abstimmung mit zivilgesellschaftlichen
      Experten entwickelt worden.
  optimumvalue:
    en: Optimum value
    de: Optimalwert
  countrycomparison:
    en: Country Comparison
    de: Ländervergleich
  countrycompintrotext:
    en: >
      This visualisation allows you to compare the performance of one country with other
      countries. For some countries there are data gaps.
    de: >
      Diese Visualisierung ermöglicht Deutschlands Nachhaltigkeit mit anderen Ländern zu
      vergleichen, soweit Daten für Länder und Indikatoren verfügbar sind.
  novalue:
    en: no value available
    de: kein Wert vorhanden
  unitunknown:
    en: unit unknown
    de: Einheit unbekannt
  indicatorunknown:
    en: indicator unknown
    de: Indikator unbekannt
  noavailableindicator:
    en: no indicator available
    de: kein Indikator vorhanden
  notavailable:
    en: not available
    de: nicht vorhanden
  monitoring:
    en: Monitoring
    de: Monitoring
  ttagenda:
    en: 2030 Agenda
    de: 2030 Agenda
  methodologyshort:
    en: Methodology
    de: Methodik
  aboutus:
    en: About us
    de: Über uns
  prototype:
    en: Prototype
    de: Prototyp
  germanysimplementationshort:
    en: Germany's performance
    de: Deutschlands Umsetzung
  individualindicators:
    en: Individual indicators
    de: Einzelindikatoren
  femarticle:
    en: The
    de: Die
  germany:
    en: Germany
    de: Deutschland
  reporting:
    en: Reporting
    de: Dokumentation
  aboutus_okf:
    en: >
      <p>The Open Knowledge Foundation Germany (OKF) is a non-profit association promoting
      the sharing of open knowledge in society. Our projects create a digital
      infrastructure for civic engagement and support citizens, journalists and
      organisations to realise their right to information, transparency
      and participation.</p>
      <p>We are part of a global network of experts and activists in 58 countries.</p>
      <p>Open Knowledge is the basis for an open and democratic society. It enables
      participation, development, education and new business models. Our activities cover
      political activism and freedom of innformation, civic tech, research, cultural
      education and a youth programme.</p>
      <p>We hold events, workshops, booksprints, hackdays
      and presentations on open knowledge and offer support and consulting.</p>
    de: >
      <p>Die Open Knowledge Foundation Deutschland (OKF DE) ist ein gemeinnütziger Verein,
      der sich für die Verbreitung von freiem Wissen in der Gesellschaft einsetzt. Unsere
      Projekte schaffen die digitale Infrastruktur für zivilgesellschaftliches Handeln und
      unterstützen Bürger, Journalisten und Organisationen dabei, ihr Recht auf
      Information, Transparenz und Beteiligung wahrzunehmen.</p>
      <p>Wir sind Teil eines internationalen Netzwerkes von Experten und Freiwilligen in
      58 Ländern.</p>
      <p>Freies Wissen bildet die Grundlage für eine offene und demokratische
      Gesellschaft. Es ermöglicht soziale Teilhabe, Entwicklung, Austausch, Bildung und
      neue Geschäftsmodelle.</p>
      <p>Unsere Arbeit erstreckt sich auf die Bereiche Politik und
      Informationsfreiheit, Civic Tech, Forschung, kulturelle Bildung und
      Jugendförderung.</p>
      <p>Wir realisieren Veranstaltungen, Workshops, Booksprints, Hackdays und
      Vorträge rund um das offene Wissen und bieten individuelle Unterstützung und
      Beratung durch unser <a href="https://okfn.de/team/">20-köpfiges Team</a>.</p>
  aboutus_okf2:
    de: >
      The work of OKF DE is funded almost exclusively through individual projects. Our
      funders are the European Union, government donors at national and local level,
      foundations, non government organisations and private donors. A detailed overview of
      our finances is presented <a href="http://okfn.de/en/verein/">here</a>.
    en: >
      Die Arbeit der OKF DE wird fast ausschließlich durch Einzelprojekte finanziert.
      Geldgeber sind die EU, staatliche Geber auf nationaler und kommunaler Ebene,
      Stiftungen, Nichtregierungsorganisationen sowie private Spender. Eine genaue
      Aufstellung unserer Finanzen findet Du <a href="http://okfn.de/verein/">hier</a>.
  aboutus_budget:
    en: >
      2030 Watch is a project of the Open Knowledge Foundation Germany. The goal of the
      project is to monitor the implementation of the sustainable development goals in EU
      and in OECD countries. The project budget for 2015 was €55,620 Euro. 73% of the
      budget was covered by the German Ministry for Economic Cooperation and
      Development(BMZ). The other donors were Welthungerhilfe (9%), Brot für die Welt /EED
      (9%) Terre des Hommes (7%) and Katholischer Fonds (ca. 2%). The rest (less than 1%)
      are individual donations. The budget for 2016 is still preliminary. Our main donors
      for 2016 are BMZ, Brot für die Welt/EED and Welthungerhilfe.
    de: >
      Das Projektbudget für 2015 war 55.620 Euro. 73% des Budgets wurden vom BMZ getragen.
      Die übrigen Finanzgeber waren Welthungerhilfe (9%), Brot für die Welt /EED (9%)
      Terre des Hommes (7%) und katholischer Fonds (ca. 2%). Der Rest (weniger als 1%)
      sind Eigenmittel. Das Budget für 2016 ist vorläufig. Nach diesem Budget ist unser
      Hauptförderer weiterhin das BMZ im Rahmen des von Engagement Global verwalteten
      Programm für Entwicklungspolitische Bildung (FEB), sowie Brot für die Welt und die
      Welthungerhilfe.
  aboutus_yearreport:
    en: Annual report (in German)
    de: Jahresbericht
  aboutus_yearfinances:
    en: Annual financial report (in German)
    de: Jahresfinanzbericht 
    
      